### ISSUE TITLE
Export Command can not be run from Console

### ISSUE THREAD

**Issue by shixinzia** [JustAHuman-xD/RecipeExporter#1]
Enter recipe_exporter instruction indicating that this command cannot be found.
The re command could not be entered.
 Command prompts such as recipe_exporter export items Error: Console may not execute this command

**Comment by JustAHuman-xD** [comment]
Yeah as the error says console cannot run the command you have to run it as a player, I'll be changing it soon but that's not a big priority atm

**Comment by JustAHuman-xD** [comment]
Latest version should have all commands working on the console except for item groups as that's localized 👍
