### ISSUE TITLE
Failing to Compile

### ISSUE THREAD

**Issue by Quinn-Suligoy** [JustAHuman-xD/RecipeExporter#4]
https://pastebin.com/pmmcA70K
Trying to compile gives me this error, still new to using spigot plugins so any help would be appreciated

**Comment by JustAHuman-xD** [comment]
Just pushed a commit which should fix it! Sorry about that the last commits I pushed to this I did on my phone so I missed an import. I'll see if I can get a proper release for this out soon, been focusing on other things recently

**Comment by Quinn-Suligoy** [comment]
Thanks so much it compiles now :)
