### ISSUE TITLE
Attempted to compile, got 29 errors. what did i do wrong?

### ISSUE THREAD

**Issue by yoopgim** [JustAHuman-xD/RecipeExporter#5]
i ran "javac SlimefunServerEssentials.java" at its directory using cmd on windows, then got the following errors

>SlimefunServerEssentials.java:3: error: package co.aikar.commands does not exist
import co.aikar.commands.BukkitCommandCompletionContext;
                        ^
SlimefunServerEssentials.java:4: error: package co.aikar.commands does not exist
import co.aikar.commands.CommandCompletions;
                        ^
SlimefunServerEssentials.java:5: error: package co.aikar.commands does not exist
import co.aikar.commands.PaperCommandManager;
                        ^
SlimefunServerEssentials.java:6: error: package lombok does not exist
import lombok.Getter;
             ^
SlimefunServerEssentials.java:7: error: package me.justahuman.slimefun_server_essentials.channels does not exist
import me.justahuman.slimefun_server_essentials.channels.AddonChannel;
                                                        ^
SlimefunServerEssentials.java:8: error: package me.justahuman.slimefun_server_essentials.channels does not exist
import me.justahuman.slimefun_server_essentials.channels.BlockChannel;
                                                        ^
SlimefunServerEssentials.java:9: error: package me.justahuman.slimefun_server_essentials.util does not exist
import me.justahuman.slimefun_server_essentials.util.Utils;
                                                    ^
SlimefunServerEssentials.java:10: error: package org.bstats.bukkit does not exist
import org.bstats.bukkit.Metrics;
                        ^
SlimefunServerEssentials.java:11: error: cannot find symbol
import org.bukkit.plugin.java.JavaPlugin;
                             ^
  symbol:   class JavaPlugin
  location: package org.bukkit.plugin.java
SlimefunServerEssentials.java:13: error: cannot find symbol
public final class SlimefunServerEssentials extends JavaPlugin {
                                                    ^
  symbol: class JavaPlugin
SlimefunServerEssentials.java:19: error: cannot find symbol
    private static AddonChannel addonChannel = null;
                   ^
  symbol:   class AddonChannel
  location: class SlimefunServerEssentials
SlimefunServerEssentials.java:22: error: cannot find symbol
    private static BlockChannel blockChannel = null;
                   ^
  symbol:   class BlockChannel
  location: class SlimefunServerEssentials
SlimefunServerEssentials.java:15: error: cannot find symbol
    @Getter
     ^
  symbol:   class Getter
  location: class SlimefunServerEssentials
SlimefunServerEssentials.java:18: error: cannot find symbol
    @Getter
     ^
  symbol:   class Getter
  location: class SlimefunServerEssentials
SlimefunServerEssentials.java:21: error: cannot find symbol
    @Getter
     ^
  symbol:   class Getter
  location: class SlimefunServerEssentials
SlimefunServerEssentials.java:24: error: method does not override or implement a method from a supertype
    @Override
    ^
SlimefunServerEssentials.java:28: error: cannot find symbol
        new Metrics(instance, 18206);
            ^
  symbol:   class Metrics
  location: class SlimefunServerEssentials
SlimefunServerEssentials.java:30: error: cannot find symbol
        final PaperCommandManager paperCommandManager = new PaperCommandManager(this);
              ^
  symbol:   class PaperCommandManager
  location: class SlimefunServerEssentials
SlimefunServerEssentials.java:30: error: cannot find symbol
        final PaperCommandManager paperCommandManager = new PaperCommandManager(this);
                                                            ^
  symbol:   class PaperCommandManager
  location: class SlimefunServerEssentials
SlimefunServerEssentials.java:31: error: cannot find symbol
        final CommandCompletions<BukkitCommandCompletionContext> commandCompletions = paperCommandManager.getCommandCompletions();
              ^
  symbol:   class CommandCompletions
  location: class SlimefunServerEssentials
SlimefunServerEssentials.java:31: error: cannot find symbol
        final CommandCompletions<BukkitCommandCompletionContext> commandCompletions = paperCommandManager.getCommandCompletions();
                                 ^
  symbol:   class BukkitCommandCompletionContext
  location: class SlimefunServerEssentials
SlimefunServerEssentials.java:32: error: cannot find symbol
        commandCompletions.registerAsyncCompletion("addons", c -> Utils.getSlimefunAddonNames());
                                                                  ^
  symbol:   variable Utils
  location: class SlimefunServerEssentials
SlimefunServerEssentials.java:33: error: cannot find symbol
        paperCommandManager.registerCommand(new CommandManager());
                                                ^
  symbol:   class CommandManager
  location: class SlimefunServerEssentials
SlimefunServerEssentials.java:35: error: cannot find symbol
        if (getConfig().getBoolean("automatic-addons", true)) {
            ^
  symbol:   method getConfig()
  location: class SlimefunServerEssentials
SlimefunServerEssentials.java:36: error: cannot find symbol
            addonChannel = new AddonChannel(getConfig().getStringList("addon-blacklist"));
                               ^
  symbol:   class AddonChannel
  location: class SlimefunServerEssentials
SlimefunServerEssentials.java:36: error: cannot find symbol
            addonChannel = new AddonChannel(getConfig().getStringList("addon-blacklist"));
                                            ^
  symbol:   method getConfig()
  location: class SlimefunServerEssentials
SlimefunServerEssentials.java:39: error: cannot find symbol
        if (getConfig().getBoolean("custom-block-textures", true)) {
            ^
  symbol:   method getConfig()
  location: class SlimefunServerEssentials
SlimefunServerEssentials.java:40: error: cannot find symbol
            blockChannel = new BlockChannel();
                               ^
  symbol:   class BlockChannel
  location: class SlimefunServerEssentials
SlimefunServerEssentials.java:44: error: method does not override or implement a method from a supertype
    @Override
    ^
29 errors

what did i do wrong?

**Comment by JustAHuman-xD** [comment]
I've put a build out in releases, just use that for now!
