### ISSUE TITLE
Console Spam & Causing Massive Lag

### ISSUE THREAD

**Issue by CassieRoseZA** [JustAHuman-xD/RecipeExporter#6]
this is probs caused by the API version set to 1.19

**Comment by JustAHuman-xD** [comment]
Yeah I'd just recommend removing the build from your server, since it’s not really in a good spot and I’m also not actively working on it

**Comment by JustAHuman-xD** [comment]
Should be fixed with: https://github.com/JustAHuman-xD/SlimefunServerEssentials/releases/tag/v0.2.0

**Comment by CassieRoseZA** [comment]
Does it support 1.20.4?
